server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo-list
    username: postgres
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

axon:
  server:
    port: 8081
  amqp:
    exchange: produtos-vendas
  eventhandling:
    processors:
      amqpEvents:
        mode: subscribing
        source: complaintEventsMethod