server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres-produtos-vendas-cqrs:5432/postgres-produtos-vendas-cqrs
    username: postgres
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

axon:
  axonserver:
    servers: axonserver:8124
  server:
    port: 8081
  amqp:
    exchange: produtos-vendas
  eventhandling:
    processors:
      amqpEvents:
        mode: subscribing
        source: complaintEventsMethod